# Generated by Django 5.2.8 on 2025-11-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='published_date',
            new_name='pub_date',
        ),
    ]
